#!/bin/sh
#
# pmset-drawing:
# from what source is the power manager drawing?
#
# Syntax:
#
#     pmset-drawing
#
# Example:
#
#     $ pmset-drawing
#     AC Power
#
# The known values are:
#
#   * AC Power
#   * Battery Power
#
# These commands are all related:
#
#   * `pmset-battery-full`
#   * `pmset-battery-percent`
#   * `pmset-drawing`
#   * `pmset-drawing-ac-power`
#   * `pmset-drawing-battery-power`
#   * `pmset-powerful`
#
# ## Tracking
#
#   * Command: pmset-drawing
#   * Version: 2.0.0
#   * Created: 2015-06-30
#   * Updated: 2017-11-02
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
pmset -g ps | sed -n "s/Now drawing from '\(.\+\).*'/\1/p"
