#!/bin/sh
#
# pmset-drawing-ac: 
# is the power manager drawing from AC power?
#
# Syntax:
#
#     pmset-drawing-ac-power
#
# Example:
#
#     $ pmset-drawing-ac-power && echo "yes" || echo "no"
#     yes
#
# These commands are all related:
#
#   * `pmset-battery-full`
#   * `pmset-battery-percent`
#   * `pmset-drawing`
#   * `pmset-drawing-ac-power`
#   * `pmset-drawing-battery-power`
#   * `pmset-powerful`
#
# ## Tracking
#
#   * Command: pmset-drawing-ac-power
#   * Version: 2.0.1
#   * Created: 2015-06-30
#   * Updated: 2017-11-02
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
pmset -g ps | grep  -qm1 "^Now drawing from 'AC Power'"
