#!/bin/sh
#
# pmset-drawing:
# from what source is the power manager drawing?
#
# Syntax:
#
#     pmset-drawing
#
# Example:
#
#     pmset-drawing
#     Now drawing from 'AC Power'
#
# The known values are:
#
#   * "Now drawing from 'AC Power'"
#   * "Now drawing from 'Battery Power'"
#
# These commands are all related:
#
#   * `pmset-battery-full`
#   * `pmset-battery-percent`
#   * `pmset-drawing`
#   * `pmset-draing-ac`
#   * `pmset-drawing-battery`
#   * `pmset-powerful`
#
# ## Tracking
#
#   * Command: pmset-drawing
#   * Version: 1.1.0
#   * Created: 2015-06-30
#   * Updated: 2017-11-01
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
pmset -g ps | head -1
