#!/bin/sh
#
# pmset-powerful: 
# is the power manager ready for powerful work?
#
# Syntax:
#
#     pmset-powerful
#
# Example:
#
#     pmset-drawing-ac && echo "yes" || echo "no"
#
# These commands are all related:
#
#   * `pmset-battery-full`
#   * `pmset-battery-percent`
#   * `pmset-drawing`
#   * `pmset-draing-ac`
#   * `pmset-drawing-battery`
#   * `pmset-powerful`
#
# ## Tracking
#
#   * Command: pmset-powerful
#   * Version: 1.1.1
#   * Created: 2015-06-30
#   * Updated: 2017-11-01
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
pmset-drawing-ac && pmset-battery-full
