#!/bin/sh
#
# pmset-powerful: 
# is the power manager ready for powerful work?
#
# Syntax:
#
#     pmset-powerful
#
# Example:
#
#     $ pmset-powerful && echo "yes" || echo "no"
#     yes
#
# These commands are all related:
#
#   * `pmset-battery-full`
#   * `pmset-battery-percent`
#   * `pmset-drawing`
#   * `pmset-drawing-ac-power`
#   * `pmset-drawing-battery-power`
#   * `pmset-powerful`
#
# ## Tracking
#
#   * Command: pmset-powerful
#   * Version: 2.0.1
#   * Created: 2015-06-30
#   * Updated: 2017-11-02
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
pmset-drawing-ac-power && pmset-battery-full
