#!/bin/sh
#
# pmset-drawing-battery: 
# is the power manager drawing from battery power?
#
# Syntax:
#
#     pmset-drawing-battery-power
#
# Example:
#
#     pmset-drawing-battery-power && echo "yes" || echo "no"
#
# These commands are all related:
#
#   * `pmset-battery-full`
#   * `pmset-battery-percent`
#   * `pmset-drawing`
#   * `pmset-drawing-ac-power`
#   * `pmset-drawing-battery-power`
#   * `pmset-powerful`
#
# ## Tracking
#
#   * Command: pmset-drawing-battery-power
#   * Version: 2.0.0
#   * Created: 2015-06-30
#   * Updated: 2017-11-02
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
pmset -g ps | grep  -q " drawing from 'Battery Power'"
